USE example;
CREATE TABLE IF NOT EXISTS jobs(
JOB_ID VARCHAR(2) NOT NULL,
JOB_TITLE VARCHAR(20) NOT NULL,
MAX_SALARY DECIMAL(5,0) ,
MIN_SALARY DECIMAL(6,0),
CHECK (MAX_SALARY<=250000)
);
DESC jobs;
DROP table jobs;
